language: php

sudo: false

php:
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

env:
  global:
    - DB_DSN="mysql:dbname=mysql;host=127.0.0.1"
    - DB_USER="root"
    - DB_PASS=""

env:
  global:
    - DB_DSN="mysql:dbname=mysql;host=127.0.0.1"
    - DB_USER="root"
    - DB_PASS=""

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit

services:
  - mysql
