language: php

sudo: false

php:
  - 7.0
  - 7.1

env:
  - DB_DSN="mysql:dbname=mysql;host=127.0.0.1"
  - DB_USER="root"
  - DB_PASS=""
before_script:
  - composer install

script:
  - phpunit

services:
  - mysql
